language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
script: mkdir build && cd build && cmake  -DINSTDIR:STRING=. -DUSE_RUN_CC_PL:BOOLEAN=OFF -DCMAKE_BUILD_TYPE:STRING=DEBUG -DUSE_CXX_11:BOOLEAN=OFF  .. && make
